upstream dev-backend {
    server 10.8.0.6:8080;
}

server {
        listen 5555;
        listen [::]:5555;

        server_name api-dev.vnnet.site;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_pass http://dev-backend;
                proxy_next_upstream error timeout http_504;
        }

}

server {
        listen 5555;
        listen [::]:5555;

        server_name jenkins.vnnet.site;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_pass http://10.8.0.6:11000;
        }

}


server {
        listen 3000;
        listen [::]:3000;

        server_name vnnet.site;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_pass http://10.8.0.6:3000;
        }

}
